apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: tonyhomsi/kub-demo-tasks:latest
          env:
            - name: AUTH_ADDRESS
              # value: "10.96.232.143"
              value: "auth-service.default"
            - name: TASKS_FOLDER
              value: tasks #creating an empty folder in the dirc tasks-api