apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  #type: ClusterIP
  #type: NodePort
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
