apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
    #- ReadOnlyMany
    #- ReadWriteMany
  hostPath:
    path: /data
    type: DirectoryOrCreate
  #persistentVolumeReclaimPolicy: Recycle
  #mountOptions:
   # - hard
    #- nfsvers=4.1
  #nfs:
  #  path: /tmp
  #  server: 172.17.0.2
